export type Ministry =
  | "ABCs"
  | "MAG"
  | "MAG_Agencies"
  | "MCCSS"
  | "Municipal_Police"
  | "POA_Courts"
  | "SolGen"
  | "TBS";

export const ministries: Ministry[] = [
  "ABCs",
  "MAG",
  "MAG_Agencies",
  "MCCSS",
  "Municipal_Police",
  "POA_Courts",
  "SolGen",
  "TBS",
];

export const divisions = {
  ABCs: ["Canadian Hearing Society"],
  MAG: [
    "Agency and Tribunal Relations",
    "Civil Law",
    "Corporate Services Management Division",
    "Court Services",
    "Criminal Law Division",
    "Indigenous Justice",
    "Modernization Division",
    "Victims and Vulnerable Persons",
  ],
  MAG_Agencies: [
    "Alcohol and Gaming Commission of Ontario (AGCO)",
    "Office of the Independent Police Review Director",
    "Ontario Human Rights Commission",
    "Tribunals Ontario-Human Rights Tribunal of Ontario",
    "Tribunals Ontario-Ontario Land Tribunal",
    "Tribunals Ontario-Ontario Parole Board",
  ],
  MCCSS: ["Youth Justice Services"],
  Municipal_Police: [
    "Akwesasne PS",
    "Barrie PS",
    "Belleville PS",
    "Brantford PS",
    "Chatham Kent PS",
    "Cobourg PS",
    "Cornwall PS",
    "Durham Regional PS",
    "Guelph PS",
    "Halton Regional PS",
    "Hamilton PS",
    "Kawartha Lakes PS",
    "Kingston PS",
    "London PS",
    "Midland PS",
    "Niagara PS",
    "North Bay PS",
    "Ottawa PS",
    "Peterborough Lakefield PS",
    "Port Hope PS",
    "Rama PS",
    "Sarnia PS",
    "Sault Ste Marie PS",
    "Six Nations PS",
    "Smith Falls PS",
    "South Simcoe PS",
    "St Thomas PS",
    "Sudbury PS",
    "Thunder Bay PS",
    "Timmins PS",
    "Toronto PS",
    "Waterloo Regional PS",
    "Wikwemikong PS",
    "Windsor PS",
    "York Regional PS",
  ],
  POA_Courts: ["York Region"],
  SolGen: [
    "COF",
    "Corporate Services",
    "Corrections",
    "Executive Offices",
    "Justice Technology Services",
    "Legal Services",
    "Office of Chief Coroner/OFPS",
    "Office of Fire Marshal",
    "Office of Fire Marshal and Emergency Management",
    "Ontario Provincial Police",
    "Public Safety",
    "Public Safety Division",
    "Public Safety Training Division",
    "(blank)",
  ],
  TBS: ["Emergency Management Ontario"],
};

export const branches = {
  "Canadian Hearing Society": ["None"],
  "Agency and Tribunal Relations": [
    "Office of the Independent Police Review Director",
    "SJTO - Human Rights Tribunal of Ontario",
    "SLASTO - Ontario Parole Board",
  ],
  "Civil Law": ["Legal Services Program Support"],
  "Corporate Services Management Division": [
    "ADAG's Office",
    "Facilities Management Branch",
  ],
  "Court Services": [
    "242 King Oshawa Court",
    "850 King Oshawa Court",
    "935 Ramsey Lake Rd",
    "Alexandria Courthouse",
    "Barrie Courthouse",
    "Belleville Court",
    "Bracebridge Court",
    "Bradford (West Gwillimbury) Courthouse",
    "Brampton (A. Grenville and William Davis) Courthouse",
    "Brantford Courthouse",
    "Brantford Ontario Court of Justice",
    "Brantford Superior Court of Justice",
    "Brockville Courthouse",
    "Burlington Courthouse",
    "Cayuga Courthouse",
    "Chatham Courthouse",
    "Chief Justice Boardroom",
    "Cobourg (Northumberland County) Courthouse",
    "Cochrane Courthouse",
    "Cornwall Courthouse",
    "Corporate Planning",
    "Dryden Courthouse",
    "Durham Region Courthouse",
    "Elgin County Courthouse",
    "Elliot Lake Courthouse",
    "Espanola Courthouse",
    "Fort Frances Courthouse",
    "Goderich Courthouse",
    "Gore Bay Courthouse",
    "Gore Bay Courthouse - SCJ Trial Offsite",
    "Guelph Courthouse (OCJ)",
    "Guelph Courthouse (SCJ)",
    "Haileybury Courthouse",
    "Hamilton (John Sopinka) Courthouse",
    "Hamilton Unified Family Courthouse",
    "Hearst Courthouse (Satellite)",
    "Kenora Courthouse",
    "Kenora Justice Centre",
    "Kingston (Frontenac County) Courthouse",
    "Kingston Courthouse (OCJ - CRIMINAL)",
    "Kingston Courthouse (SCJ - FAMILY)",
    "Kirkland Lake Courthouse",
    "Kitchener Court",
    "Lindsay Courthouse",
    "London Courthouse",
    "London Justice Center",
    "L'Orignal Courthouse",
    "L'Orignal Courthouse (OCJ)",
    "L'Orignal Courthouse (SCJ)",
    "Midland Courthouse",
    "Milton Courthouse",
    "Napanee Courthouse",
    "Newmarket Courthouse",
    "North Bay Courthouse",
    "Ontario Court of Justice",
    "Ontario Court of Justice – Toronto",
    "Orangeville Courthouse",
    "Orillia Courthouse",
    "Osgoode Hall",
    "Ottawa Courthouse",
    "Ottawa CSD Regional Office",
    "Owen Sound Courthouse",
    "Parry Sound Courthouse",
    "Pembroke (Renfrew County) Courthouse",
    "Pembroke Courthouse",
    "Perth Courthouse",
    "Peterborough Courthouse",
    "Picton Courthouse",
    "Picton Courthouse - OCJ",
    "Picton Courthouse - SCJ",
    "Program Management Branch",
    "Quinte Consolidated Courthouse",
    "Quinte Regional Courthouse",
    "Red Lake Courthouse",
    "Sarnia Courthouse",
    "Sault Ste Marie Courthouse",
    "Simcoe Courthouse",
    "Sioux Lookout Courthouse",
    "St Catharines Courthouse",
    "St. Thomas Courthouse",
    "Stratford Courthouse",
    "Sudbury Courthouse",
    "Sudbury Courthouse - Cedar St",
    "Sudbury Courthouse - Elm St",
    "Sudbury Courthouse - OCJ",
    "Sudbury Courthouse - SCJ",
    "Superior Court of Justice",
    "Superior Court of Justice- Renfrew",
    "TBD",
    "Thunder Bay Courthouse",
    "Timmins Courthouse (OCJ)",
    "Timmins Courthouse (SCJ)",
    "Toronto - 1000 Finch (Metro North) Courthouse",
    "Toronto - 1911 Eglinton Courthouse",
    "Toronto - 2201 Finch (Metro West) Courthouse",
    "Toronto - 311 Jarvis Court",
    "Toronto - 330 University Courthouse",
    "Toronto - 361 University Courthouse",
    "Toronto - 393 University Courthouse",
    "Toronto - 444 Yonge (College Park) Courthouse",
    "Toronto - 47 Sheppard Courthouse",
    "Toronto - 60 Queen (Old City Hall) Courthouse",
    "Toronto Courthouse",
    "Trevor to assign",
    "Walkerton (County of Bruce) Courthouse",
    "Walkerton Courthouse",
    "Waterloo Region Courthouse",
    "Welland Courthouse",
    "Windsor Courthouse (OCJ)",
    "Windsor Courthouse (SCJ)",
    "Woodstock (Oxford County) Courthouse",
    "(blank)",
  ],
  "Criminal Law Division": [
    "720 Bay",
    "COF",
    "Crown's Office - 393 University",
    "Crown's Office - North Region",
    "Kenora Courthouse",
    "Sudbury Courthouse - Cedar St/ North Region Criminal Law office",
    "Timmins Crown Office",
  ],
  "Indigenous Justice": ["N/A"],
  "Modernization Division": [
    "Analytics Branch",
    "Business Transformation Office - Innovation Office",
    "PMO",
  ],
  "Victims and Vulnerable Persons": [
    "North Region Office",
    "St Catharines Courthouse",
    "Timmins Courthouse (OCJ)",
    "Woodstock (Oxford County) Courthouse",
    "(blank)",
  ],
  "Alcohol and Gaming Commission of Ontario (AGCO)": ["None"],
  "Office of the Independent Police Review Director": ["None"],
  "Ontario Human Rights Commission": ["None"],
  "Tribunals Ontario-Human Rights Tribunal of Ontario": ["None"],
  "Tribunals Ontario-Ontario Land Tribunal": ["Policy Division"],
  "Tribunals Ontario-Ontario Parole Board": ["None"],
  "Youth Justice Services": [
    "Arrell Youth Centre",
    "Brookside Youth Centre",
    "Cecil Facer Youth Centre",
    "Corporate",
    "Craigwood Youth Services",
    "Donald Doucet Youth Centre",
    "Ge-Da-Gi-Binez Y. C.",
    "Genest Maurice YC",
    "JJ Kelso Y.C.",
    "Justice Ronald Lester Y.C.",
    "Kennedy House Y.C.",
    "Near North Youth Center",
    "Peninsula YC",
    "Pinegar Youth Centre",
    "Portage Y.C.",
    "Ray of Hope YC",
    "Roy McMurtry YC",
    "Sprucedale Youth Centre",
    "Sundance Y.C.",
    "Syl Apps Youth Centre",
    "William Hay Y.C.",
    "(blank)",
  ],
  "Akwesasne PS": ["Akwesasne Mohawk Police Detachment"],
  "Barrie PS": ["Detachment"],
  "Belleville PS": ["Detachment"],
  "Brantford PS": ["Detachment"],
  "Chatham Kent PS": ["Detachment"],
  "Cobourg PS": ["Detachment"],
  "Cornwall PS": ["Detachment"],
  "Durham Regional PS": ["Detachment"],
  "Guelph PS": ["Detachment"],
  "Halton Regional PS": ["Detachment"],
  "Hamilton PS": ["Detachment"],
  "Kawartha Lakes PS": ["Detachment"],
  "Kingston PS": ["Detachment"],
  "London PS": ["Detachment"],
  "Midland PS": ["Detachment"],
  "Niagara PS": ["Detachment"],
  "North Bay PS": ["Detachment"],
  "Ottawa PS": ["Detachment"],
  "Peterborough Lakefield PS": ["Peterborough Police Station"],
  "Port Hope PS": ["Detachment"],
  "Rama PS": ["Detachment"],
  "Sarnia PS": ["Detachment"],
  "Sault Ste Marie PS": ["Detachment"],
  "Six Nations PS": ["Detachment"],
  "Smith Falls PS": ["Detachment"],
  "South Simcoe PS": ["Detachment"],
  "St Thomas PS": ["Detachment"],
  "Sudbury PS": ["Detachment"],
  "Thunder Bay PS": ["Detachment"],
  "Timmins PS": ["Detachment"],
  "Toronto PS": [
    "14 Division",
    "23 Division",
    "32 Division",
    "41 Division",
    "43 Division",
    "51 Division",
  ],
  "Waterloo Regional PS": ["Central Division (Kitchener) Detachment"],
  "Wikwemikong PS": ["Detachment"],
  "Windsor PS": ["Detachment"],
  "York Regional PS": [
    "Detachment",
    "YRPS District 2",
    "YRPS District 3",
    "YRPS District 4",
    "YRPS District 5",
  ],
  "York Region": ["York Region Court", "York Region Provincial Offences Court"],
  COF: ["None"],
  "Corporate Services": ["Office of the Assistant Deputy Ministerone"],
  Corrections: [
    "Algoma Treatment & Remand Centre",
    "Brantford Jail",
    "Brockville Jail",
    "Central East Correctional Centre",
    "Central North Correctional Centre",
    "Central Regional Office",
    "Chatham Jail",
    "Correctional Services Oversight & Investigations",
    "Eastern Regional Office",
    "Elgin-Middlesex Detention Centre",
    "Fort Frances Jail",
    "Hamilton-Wentworth Detention Centre",
    "Kenora Jail",
    "Maplehurst Correctional Complex",
    "Monteith Correctional Complex",
    "Niagara Detention Centre",
    "North Bay Jail",
    "Northern Regional Office",
    "Ottawa-Carleton Detention Centre",
    "Owen Sound Jail",
    "Quinte Detention Centre",
    "Red Lake Probation and Parole",
    "Sarnia Jail",
    "South West Detention Centre",
    "Stratford Jail",
    "Sudbury Jail",
    "Thunder Bay Correctional Centre",
    "Thunder Bay Jail",
    "Toronto East Detention Centre",
    "Toronto Jail",
    "Toronto Jail ,The Don",
    "Toronto South Detention Centre",
    "Toronto West Detention Centre",
    "Vanier Centre for Women",
    "Walkerton Jail",
    "Western Regional Office",
    "Windsor Jail",
    "(blank)",
  ],
  "Executive Offices": [
    "CAO BR",
    "Constituency Office",
    "DMO Community Safety",
    "DMO Correctional Services",
    "Minister Boardroom",
    "Minister BR",
    "Solicitor General Office",
  ],
  "Justice Technology Services": [
    "Bell Testing for Cloud/Pexip",
    "Government Mobile Communications",
    "JVN - JVN-ME on a Cart Rental",
    "JVN - Video in a Box",
    "North Bay",
    "Toronto",
    "Toronto - JVN",
  ],
  "Legal Services": ["N/A"],
  "Office of Chief Coroner/OFPS": [
    "Brampton",
    "Forensic Services and Coroners Complex",
    "Guelph",
    "Hamilton",
    "Kenora",
    "Kingston",
    "London",
    "Ottawa",
    "Ottawa",
    "Sudbury",
    "Thunder Bay",
    "Toronto",
  ],
  "Office of Fire Marshal": [
    "Forensic Services and Coroners Complex",
    "Midhurst",
    "Thunder Bay",
  ],
  "Office of Fire Marshal and Emergency Management": [
    "Gravenhurst",
    "MEOC 25 Grosvenor",
    "Sudbury",
    "Toronto",
  ],
  "Ontario Provincial Police": [
    "Almaguin Highlands Detachment",
    "Armstrong Detachment",
    "Arnprior",
    "Bancroft Detachment",
    "Bracebridge Detachment",
    "Brant County Detachment",
    "Caledon Detachment",
    "Central Hastings Detachment",
    "City of Kawartha Lakes Detachment",
    "Collingwood Detachment",
    "Dufferin Detachment",
    "East Algoma (Blind River) Detachment",
    "East Region Headquarters",
    "Elgin County Detachment",
    "Forensic Identification & Photographic Services",
    "Fort Frances Detachment",
    "Frontenac Detachment",
    "General Headquarters - OPP GHQ",
    "Greenstone Detachment",
    "Grenville Detachment",
    "Haldimand County Detachment",
    "Haliburton Highlands Detachment",
    "Hawkesbury Detachment",
    "Highway Safety Division Headquarters",
    "HSD-Bolton",
    "Huntsville Detachment",
    "Huron (Goderich) Detachment",
    "Huron Detachment",
    "Huronia West Detachment",
    "Iroquois Falls Detachment",
    "James Bay (Cochrane) Detachment",
    "James Bay (Hearst) Detachment",
    "James Bay (Kapuskasing) Detachment",
    "James Bay (Moosonee) Detachment",
    "Killaloe Detachment",
    "Kirkland Lake Detachment",
    "Lambton County Detachment",
    "Lanark County Detachment",
    "Leeds County (Brockville) Detachment",
    "London OPP PCC UC",
    "Marathon Detachment",
    "Napanee Detachment",
    "Nipigon Detachment",
    "Norfolk County Detachment",
    "North East Region Headquarters",
    "North West Region Headquarters",
    "Northumberland (Cobourg) Detachment",
    "Nottawasaga Detachment",
    "OPP Academy Belleville",
    "OPP Academy Dryden",
    "OPP Academy Kapuskasing",
    "OPP Academy Kenora",
    "OPP Academy Leamington",
    "OPP Academy London",
    "OPP Academy Mississauga",
    "OPP Academy Mount Forest",
    "OPP Academy North Bay",
    "OPP Academy Smith Falls",
    "OPP Academy SSM",
    "OPP Academy Thunder Bay",
    "OPP Academy Tillsonburg",
    "OPP EOC",
    "OPP OCEB",
    "OPP PWEU",
    "Orillia Detachment",
    "Orillia OPP PCC UC",
    "Pembroke Detachment",
    "Peterborough County Detachment",
    "Prince Edward Detachment",
    "Provincial Communications Centre - London",
    "Provincial Communications Centre - North Bay",
    "Provincial Communications Centre - Orillia",
    "Provincial Communications Centre - Smith Falls",
    "Provincial Communications Centre - Thunder Bay",
    "Provincial Operations Centre (OPP POC)",
    "Quinte West Detachment",
    "Red Lake Detachment",
    "Renfrew Detachment",
    "Russell County Detachment",
    "Sault Ste. Marie Detachment",
    "Sioux lookout Detachment",
    "South Bruce Detachment",
    "Southern Georgian Bay Detachment",
    "Stormont Dundas and Glengarry Detachment",
    "Superior East (Chapleau) Detachment",
    "Superior East (Wawa) Detachment",
    "Temiskaming Detachment",
    "Thunder Bay Detachment",
    "Upper Ottawa Valley Detachment",
    "Wellington County (Palmerston) Detachment",
    "Wellington County (Rockwood) Detachment",
    "West Parry Sound Detachment",
    "Western Region Headquarters",
    "(blank)",
  ],
  "Public Safety": ["Criminal Intelligence Service Ontario"],
  "Public Safety Division": [
    "CFS - Forensic Services and Coroners Complex",
    "CFS - Sault Ste Marie",
    "Criminal Intelligence Service Ontario",
    "External Relations",
  ],
  "Public Safety Training Division": [
    "Ontario Correctional Services College",
    "Ontario Police College",
  ],
  blank: ["OPP Middlesex", "(blank)"],
  "Emergency Management Ontario": [
    "Forensic Services and Coroners Complex",
    "Toronto - 25 Grosvenor",
  ],
};
